filelist:
- "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016/WJetsToLNu-amcatnloFXFX/nanoHTT_0.root"
- "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016/WJetsToLNu-amcatnloFXFX/nanoHTT_1.root"
- "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016/WJetsToLNu-amcatnloFXFX/nanoHTT_2.root"
- "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016/WJetsToLNu-amcatnloFXFX/nanoHTT_3.root"
- "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016/WJetsToLNu-amcatnloFXFX/nanoHTT_4.root"
- "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/HLepRare/HTT_skim_v1/Run2_2016/WJetsToLNu-amcatnloFXFX/nanoHTT_5.root"
